### ISSUE TITLE
Question: I have Error In "pip3 install -r requirements.txt", No matching distribution found for onnx==1.8.1

### ISSUE THREAD

**Issue by majidsd** [ifzhang/ByteTrack#102]
### Specification

-  Ubuntu 18.04.6 LTS
-  Python 3.9 (In Environment using Anaconda 4.10.3)

### What was done

1. git clone https://github.com/ifzhang/ByteTrack.git (Good)
2. cd ByteTrack (Good)
3. pip3 install -r requirements.txt (Error)

### What I get:
'Collecting onnx==1.8.1
  Using cached onnx-1.8.1.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/anaconda3/envs/ByteTrack39/bin/python /home/anaconda3/envs/ByteTrack39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpnjskbv7q
       cwd: /tmp/pip-install-6bn8r3bf/onnx_cfd45788e38244ee809a7d213d4e2c39
  Complete output (19 lines):
  fatal: not a git repository (or any of the parent directories): .git
  Traceback (most recent call last):
    File "/home/anaconda3/envs/ByteTrack39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/anaconda3/envs/ByteTrack39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/anaconda3/envs/ByteTrack39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ebj66tek/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-ebj66tek/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ebj66tek/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-ebj66tek/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 75, in <module>
      assert CMAKE, 'Could not find "cmake" executable!'
  AssertionError: Could not find "cmake" executable!
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/8d/c924f54e19ec71543c18658d86e8337579d5a784bd524b7f18e2e2cd6f17/onnx-1.8.1.tar.gz#sha256=9d65c52009a90499f8c25fdfe5acda3ac88efe0788eb1d5f2575a989277145fb (from https://pypi.org/simple/onnx/). Command errored out with exit status 1: /home/anaconda3/envs/ByteTrack39/bin/python /home/anaconda3/envs/ByteTrack39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpnjskbv7q Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement onnx==1.8.1 (from versions: 0.1, 0.2, 0.2.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2)
ERROR: No matching distribution found for onnx==1.8.1'

### Any Help?

**Comment by divyajaincs** [comment]
Just create a virtual environment with python 3.6.

**Comment by majidsd** [comment]
Thanks, it was version issue, it's working now.
