### ISSUE TITLE
TypeError: Caught TypeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by shuyu888** [ifzhang/ByteTrack#176]
2022-04-21 16:30:09 | INFO     | yolox.data.datasets.mot:43 - loading annotations into memory...
2022-04-21 16:30:09 | INFO     | yolox.data.datasets.mot:43 - Done (t=0.00s)
2022-04-21 16:30:09 | INFO     | pycocotools.coco:88 - creating index...
2022-04-21 16:30:09 | INFO     | pycocotools.coco:88 - index created!
2022-04-21 16:30:09 | INFO     | yolox.core.trainer:149 - init prefetcher, this might take one minute or less...
2022-04-21 16:30:11 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (3566), thread 'MainThread' (139726425002176):
Traceback (most recent call last):

  File "tools/train.py", line 126, in <module>
    launch(
    m <function launch at 0x7f14358bea60>
    ...........................................
File "/home/ubuntu/anaconda3/envs/bytetrack/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
          m TypeError('Caught TypeError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/home/ubunt...

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/bytetrack/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/bytetrack/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/ubuntu/anaconda3/envs/bytetrack/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 180, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>

**Comment by shuyu888** [comment]
anybody help????

**Comment by YamacTan** [comment]
Same problem, cannot start any training processes. Any updates? @shuyu888

**Comment by shuyu888** [comment]
it is a datasets problem
done by pip install yolox

**Comment by shuyu888** [comment]
you can reinstall the yolox file ,it will work
