### ISSUE TITLE
AttributeError: 'STrack' object has no attribute '_count

### ISSUE THREAD

**Issue by feiyang-hku** [ifzhang/ByteTrack#210]
Traceback (most recent call last):
  File "tools/demo_track.py", line 372, in <module>
    main(exp, args)
  File "tools/demo_track.py", line 365, in main
    imageflow_demo(predictor, vis_folder, current_time, args)
  File "tools/demo_track.py", line 263, in imageflow_demo
    online_targets = tracker.update(outputs[0], [img_info['height'], img_info['width']], exp.test_size)
  File "/content/ByteTrack/yolox/tracker/byte_tracker.py", line 268, in update
    track.activate(self.kalman_filter, self.frame_id)
  File "/content/ByteTrack/yolox/tracker/byte_tracker.py", line 48, in activate
    self.track_id = self.next_id()
  File "/content/ByteTrack/yolox/tracker/basetrack.py", line 36, in next_id
    self._count += 1
AttributeError: 'STrack' object has no attribute '_count'

**Comment by feiyang-hku** [comment]
Something seems to be wrong with the code...I was able to run the code yesterday. But today this error message popped out. I have tried creating a new conda environment and installed the dependencies again but is facing the same problem. Please help!

**Comment by sr99622** [comment]
For some reason, the inheritance doesn't work on this class,  You can get around it by adding a reference In byte_tracker.py to _count in the STrack.__init__ like so

```
class STrack(BaseTrack):
    shared_kalman = KalmanFilter()
    def __init__(self, tlwh, score):
        self._count = 0
```

**Comment by wangxiyang2022** [comment]
Hello, may I ask whether this problem has been solved? I have also encountered this problem.

**Comment by feiyang-hku** [comment]
I was able to work around it by git cloning from an older commit (The one on May 13, 2022). Please see [this post](https://github.com/ifzhang/ByteTrack/pull/190#issuecomment-1166476611) for your reference. The command to git clone from an older commit can be found at https://stackoverflow.com/questions/3555107/git-clone-particular-version-of-remote-repository.

**Comment by wangxiyang2022** [comment]
Thank you very much!

**Comment by Breezewrf** [comment]
> I was able to work around it by git cloning from an older commit (The one on May 13, 2022). Please see [this post](https://github.com/ifzhang/ByteTrack/pull/190#issuecomment-1166476611) for your reference. The command to git clone from an older commit can be found at https://stackoverflow.com/questions/3555107/git-clone-particular-version-of-remote-repository.

THX！

**Comment by JonathanFK981** [comment]
you need to replace yolox with the previous version

**Comment by LIN-HAN-981120** [comment]
> you need to replace yolox with the previous version
how can i do that？  thx！

**Comment by PranvQT** [comment]
You have to add  the super().__init__ in the STrack so it can access the baseclass variables

**Comment by jasons1425** [comment]
I think this issue cannot be simply resolved by adding the super().__init__() method in the STrack class. Doing so seems to lead to issue #219. Checking out at the previous commit seems to be a better option in the current stage. My script works fine at the previous commit `2c082be`

**Comment by Breezewrf** [comment]
> I think this issue cannot be simply resolved by adding the super().**init**() method in the STrack class. Doing so seems to lead to issue #219. Checking out at the previous commit seems to be a better option in the current stage. My script works fine at the previous commit `2c082be`

hello I have met the same problem that only single box is output, could you please tell me some details about your solution? since I checkout the commit 2c082be, but it seems can't work, still return _'STrack' object has no attribute '_count'_

**Comment by PranvQT** [comment]
Hi @Breezewrf the _count variable is not useful..what I did was I created a self.id_count for the bytetracker class and then passed it as an argument to the function call where we creat the new tracks and assigned that self.id_counter to the track_ID and then incremented the variable

**Comment by PranvQT** [comment]
Yes @jasons1425 you are right I faced the same issue but I added a new variable for counting the objects so that got resolved.

**Comment by Breezewrf** [comment]
> Hi @Breezewrf the _count variable is not useful..what I did was I created a self.id_count for the bytetracker class and then passed it as an argument to the function call where we creat the new tracks and assigned that self.id_counter to the track_ID and then incremented the variable

Thanks a lot! problem got resolved

**Comment by jasons1425** [comment]
Thank you @PranvQT. The problem is likely because each STrack object has its own track_id counting instead of the class-level one, so different tracks for the same ByteTracker object are sharing the same track_id.

To count the number of tracks in each ByteTracker object without relying on the BaseTrack class attributes, I have added an `itertools.count()` as the STrack counter inside the ByteTracker class. This argument is passed to the BaseTrack class so that whenever the next_id() method is called, the latest track id (count) can be fetched from this generator.

**Comment by nikky4D** [comment]
I'm new to bytetrack. Can I see your code to see what changes should be made to get it to run over a video

>

**Comment by nikky4D** [comment]
I'm new to bytetrack. Can I see your code to see what changes should be made to get it to run over a video
> Thank you @PranvQT. The problem is likely because each STrack object has its own track_id counting instead of the class-level one, so different tracks for the same ByteTracker object are sharing the same track_id.
> 
> To count the number of tracks in each ByteTracker object without relying on the BaseTrack class attributes, I have added an `itertools.count()` as the STrack counter inside the ByteTracker class. This argument is passed to the BaseTrack class so that whenever the next_id() method is called, the latest track id (count) can be fetched from this generator.

**Comment by jasons1425** [comment]
I didn't make many changes honestly. Just added a counter to count the track ids for each ByteTracker. You can find the changes in this [pull request](https://github.com/ifzhang/ByteTrack/pull/220).

The modified scripts work fine in my local environment, but I would recommend you to just pull the main branch which has been recently reverted to get rid of this issue :)

**Comment by feiyang-hku** [comment]
Hi Yifu,

Thank you so much for your prompt reply!

I tried to add the line “self._count = 0” to byte_tracker.py as you have suggested. The code can now run, but the algorithm can only detect and track only one person (ID 1) in a scene full of people.

***@***.***

May I know what other steps I need to take if I want to detect and track all people in the scene?

Thanks again for your kind help!

Sincerely,

Feiyang

From: sr99622 ***@***.***>
Date: Sunday, June 26, 2022 at 12:50 AM
To: ifzhang/ByteTrack ***@***.***>
Cc: feiyang-hku ***@***.***>, Author ***@***.***>
Subject: Re: [ifzhang/ByteTrack] AttributeError: 'STrack' object has no attribute '_count (Issue #210)

For some reason, the inheritance doesn't work on this class, You can get around it by adding a reference In byte_tracker.py to _count in the STrack.init like so

class STrack(BaseTrack):

    shared_kalman = KalmanFilter()

    def __init__(self, tlwh, score):

        self._count = 0
