### ISSUE TITLE
pip3 install -q -r requirements.txt - AssertionError: Could not find "cmake" executable!

### ISSUE THREAD

**Issue by emilianocds** [ifzhang/ByteTrack#347]
Mac M1 Python 3.11
**(.venv) ➜  ByteTrack git:(main) pip3 install -q -r requirements.txt**                  
  ```
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "/Users/emilianosch/develop/ai/pruebas/yolov/yolov8-fastapi/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/emilianosch/develop/ai/pruebas/yolov/yolov8-fastapi/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/emilianosch/develop/ai/pruebas/yolov/yolov8-fastapi/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yp/t00p31s55w7d4bzkn5wz2zzm0000gn/T/pip-build-env-e2q4tidz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yp/t00p31s55w7d4bzkn5wz2zzm0000gn/T/pip-build-env-e2q4tidz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/yp/t00p31s55w7d4bzkn5wz2zzm0000gn/T/pip-build-env-e2q4tidz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yp/t00p31s55w7d4bzkn5wz2zzm0000gn/T/pip-build-env-e2q4tidz/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
      AssertionError: Could not find "cmake" executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by xiaoyangl9413** [comment]
Wanted to know if someone is able to solve this problem. I am facing the same.

**Comment by lw-kong** [comment]
I was using conda so I installed cmake by
`conda install cmake`
and it worked for me

**Comment by linshuai0** [comment]
> I was using conda so I installed cmake by `conda install cmake` and it worked for me

Thank you very much!It's helpful. My problem has been solved
