### ISSUE TITLE
is it possible to use your trained model just for detection purpose ?

### ISSUE THREAD

**Issue by ssbilakeri** [ifzhang/ByteTrack#61]

**Comment by pedromoraesh** [comment]
Of course, you can use it. The detection part is the base for good tracking performance. In this case, they aim to use almost every detection box to improve the tracking step. With this in mind, you can use the model just for detection without sending the boxes to the tracker.

**Comment by ssbilakeri** [comment]
Thank you for your response.

I have used your trained model on mix dataset  as a detector with the
deepsort tracker. Though it is not related to ByteTracker . would you find
any reason for the below traceback.

please help me to fix it

Traceback (most recent call last):
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/evaluation_singlcam.py",
line 293, in <module>
    det.detect()
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/evaluation_singlcam.py",
line 183, in detect
    outputs = self.deepsort.update(bbox_xywh, scores, img0)
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/deep_sort/deep_sort/deep_sort.py",
line 30, in update
    features = self._get_features(bbox_xywh, ori_img)
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/deep_sort/deep_sort/deep_sort.py",
line 111, in _get_features
    features = self.extractor(im_crops)
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/deep_sort/deep_sort/deep/feature_extractor.py",
line 44, in __call__
    im_batch = self._preprocess(im_crops)
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/deep_sort/deep_sort/deep/feature_extractor.py",
line 38, in _preprocess
    im_batch = torch.cat([self.norm(_resize(im,
self.size)).unsqueeze(0) for im in im_crops], dim=0).float()
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/deep_sort/deep_sort/deep/feature_extractor.py",
line 38, in <listcomp>
    im_batch = torch.cat([self.norm(_resize(im,
self.size)).unsqueeze(0) for im in im_crops], dim=0).float()
  File "/content/drive/MyDrive/working_code_on_backbone_yolox/deep_sort/deep_sort/deep/feature_extractor.py",
line 36, in _resize
    return cv2.resize(im.astype(np.float32)/255., size)
cv2.error: OpenCV(4.1.2)
/io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion
failed) !ssize.empty() in function 'resize'

**Comment by ssbilakeri** [comment]
for imagePath in imagePaths:
    # load the image, pre-process it, and store it in the data list
    print(imagePath)  #here I have printed the imagename
    image = cv2.imread(imagePath)
    image = cv2.resize(image, (28, 28))   # 28, 28
    image = img_to_array(image)
    data.append(image)


if(type(image) == type(None)):
    passelse:
    image = cv2.resize(image, (h, w), interpolation=cv2.INTER_AREA)




import cv2

image = cv2.imread('noexist.jpg')try:
    resize = cv2.resize(image, (64,64))except cv2.error as e:
    print('Invalid frame!')
cv2.waitKey()

**Comment by zxchang-1** [comment]
> 

I had the same problem，I have used his trained model on mix dataset  as a detector with the
deepsort tracker too. I wonder if you have solved your problem



Traceback (most recent call last):
  File "C:/Users/zxc/Desktop/ByteTrack-main/tools/demo_track.py", line 558, in <module>
    main(exp, args)
  File "C:/Users/zxc/Desktop/ByteTrack-main/tools/demo_track.py", line 549, in main
    image_demo_deepsort2(predictor, vis_folder, current_time, args)
  File "C:/Users/zxc/Desktop/ByteTrack-main/tools/demo_track.py", line 378, in image_demo_deepsort2
    outputs = deepsort.update((torch.Tensor(bbox_xywh)), (torch.Tensor(confs)), img_info['raw_img'])
  File "C:\Users\zxc\Desktop\ByteTrack-main\deep_sort\deep_sort.py", line 29, in update
    features = self._get_features(bbox_xywh, ori_img)
  File "C:\Users\zxc\Desktop\ByteTrack-main\deep_sort\deep_sort.py", line 99, in _get_features
    features = self.extractor(im_crops)
  File "C:\Users\zxc\Desktop\ByteTrack-main\deep_sort\deep\feature_extractor.py", line 45, in __call__
    im_batch = self._preprocess(im_crops)
  File "C:\Users\zxc\Desktop\ByteTrack-main\deep_sort\deep\feature_extractor.py", line 40, in _preprocess
    im_batch = torch.cat([self.norm(_resize(im, self.size)).unsqueeze(0) for im in im_crops], dim=0).float()
  File "C:\Users\zxc\Desktop\ByteTrack-main\deep_sort\deep\feature_extractor.py", line 40, in <listcomp>
    im_batch = torch.cat([self.norm(_resize(im, self.size)).unsqueeze(0) for im in im_crops], dim=0).float()
  File "C:\Users\zxc\Desktop\ByteTrack-main\deep_sort\deep\feature_extractor.py", line 37, in _resize
    a=cv2.resize(im.astype(np.float32)/255., size)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
