### ISSUE TITLE
program not working due to C++ building error?

### ISSUE THREAD

**Issue by marcIT** [ifzhang/ByteTrack#72]
I have installed all requirements on a Jetson Nano with only 4GB RAM, Ubuntu 18.04 LTS. After starting the demo cmd below the RAM usages of "python" process increases until ~ 1.2 GB then max. RAM is reached and it gets killed.

How much RAM does process "python" needs on your machine?
Do you have an idea how to reduce RAM needed / what affects RAM usage?

```
$ python3 tools/demo_track.py video -f exps/example/mot/yolox_x_mix_det.py -c pretrained/bytetrack_x_mot17.pth.tar --fp16 --fuse --save_result

2021-11-12 11:56:48.154 | INFO     | __main__:main:298 - Args: Namespace(camid=0, ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=None, demo='video', device='gpu', exp_file='exps/example/mot/yolox_x_mix_det.py', experiment_name='yolox_x_mix_det', fp16=True, fuse=True, match_thresh=0.8, min_box_area=10, mot20=False, name=None, nms=None, path='./videos/palace.mp4', save_result=True, track_buffer=30, track_thresh=0.5, trt=False, tsize=None)

/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /media/nvidia/NVME/pytorch/pytorch-v1.9.0/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)

2021-11-12 11:56:52.641 | INFO     | __main__:main:308 - Model Summary: Params: 99.00M, Gflops: 791.73
Killed
```

**Comment by marcIT** [comment]
Okay, I increased my swap and it does not get killed anymore.

Now, it runs until the output video file is created. Then I get an error about torch and torchvision incompatibility but I have used corresponding versions: torch 1.9 and torchvision 1.10. 

```
$ python3 tools/demo_track.py video -f exps/example/mot/yolox_x_mix_det.py -c pretrained/bytetrack_x_mot17.pth.tar --fp16 --save_result
 | INFO     | __main__:main:298 - Args: Namespace(camid=0, ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=None, demo='video', device='gpu', exp_file='exps/example/mot/yolox_x_mix_det.py', experiment_name='yolox_x_mix_det', fp16=True, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, name=None, nms=None, path='./videos/palace.mp4', save_result=True, track_buffer=30, track_thresh=0.5, trt=False, tsize=None)

/home/mv/miniconda3/envs/Env/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /media/nvidia/NVME/pytorch/pytorch-v1.9.0/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)

| INFO     | __main__:main:308 - Model Summary: Params: 99.00M, Gflops: 791.73
| INFO     | __main__:main:319 - loading checkpoint
| INFO     | __main__:main:323 - loaded checkpoint done.
| INFO     | __main__:imageflow_demo:240 - video save_path is ./YOLOX_outputs/yolox_x_mix_det/track_vis/2021_11_13/palace.mp4
| INFO     | __main__:imageflow_demo:250 - Processing frame 0 (100000.00 fps)
Traceback (most recent call last):
  File "tools/demo_track.py", line 357, in <module>
    main(exp, args)
  File "tools/demo_track.py", line 350, in main
    imageflow_demo(predictor, vis_folder, current_time, args)
  File "tools/demo_track.py", line 253, in imageflow_demo
    outputs, img_info = predictor.inference(frame, timer)
  File "tools/demo_track.py", line 170, in inference
    outputs, self.num_classes, self.confthre, self.nmsthre
  File "/home/mv/Documents/ByteTrack/yolox/utils/boxes.py", line 64, in postprocess
    nms_thre,
  File "/home/mv/miniconda3/envs/Env/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 68, in batched_nms
    return _batched_nms_coordinate_trick(boxes, scores, idxs, iou_threshold)
  File "/home/mv/miniconda3/envs/Env/lib/python3.6/site-packages/torch/jit/_trace.py", line 1112, in wrapper
    return fn(*args, **kwargs)
  File "/home/mv/miniconda3/envs/Env/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 87, in _batched_nms_coordinate_trick
    keep = nms(boxes_for_nms, scores, iou_threshold)
  File "/home/mv/miniconda3/envs/Env/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 34, in nms
    _assert_has_ops()
  File "/home/mv/miniconda3/envs/Env/lib/python3.6/site-packages/torchvision/extension.py", line 63, in _assert_has_ops
    "Couldn't load custom C++ ops. This can happen if your PyTorch and "
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```

**Could that be an issue caused by the C++ build warnings and it is not correctly build?**

```
$ python3 setup.py develop
running develop
running egg_info
creating yolox.egg-info
writing yolox.egg-info/PKG-INFO
writing dependency_links to yolox.egg-info/dependency_links.txt
writing top-level names to yolox.egg-info/top_level.txt
writing manifest file 'yolox.egg-info/SOURCES.txt'
package init file 'deploy/__init__.py' not found (or not a regular file)
package init file 'videos/__init__.py' not found (or not a regular file)
package init file 'exps/__init__.py' not found (or not a regular file)
package init file 'datasets/__init__.py' not found (or not a regular file)
package init file 'tutorials/__init__.py' not found (or not a regular file)
package init file 'pretrained/__init__.py' not found (or not a regular file)
package init file 'tools/__init__.py' not found (or not a regular file)
package init file 'assets/__init__.py' not found (or not a regular file)
package init file 'deploy/ncnn/__init__.py' not found (or not a regular file)
package init file 'deploy/TensorRT/__init__.py' not found (or not a regular file)
package init file 'deploy/ONNXRuntime/__init__.py' not found (or not a regular file)
package init file 'deploy/ncnn/cpp/__init__.py' not found (or not a regular file)
package init file 'deploy/ncnn/cpp/include/__init__.py' not found (or not a regular file)
package init file 'deploy/ncnn/cpp/src/__init__.py' not found (or not a regular file)
package init file 'deploy/TensorRT/python/__init__.py' not found (or not a regular file)
package init file 'deploy/TensorRT/cpp/__init__.py' not found (or not a regular file)
package init file 'deploy/TensorRT/cpp/include/__init__.py' not found (or not a regular file)
package init file 'deploy/TensorRT/cpp/src/__init__.py' not found (or not a regular file)
package init file 'yolox/sort_tracker/__init__.py' not found (or not a regular file)
package init file 'yolox/deepsort_tracker/__init__.py' not found (or not a regular file)
package init file 'yolox/tracker/__init__.py' not found (or not a regular file)
package init file 'yolox/motdt_tracker/__init__.py' not found (or not a regular file)
package init file 'yolox/tracking_utils/__init__.py' not found (or not a regular file)
package init file 'yolox/layers/csrc/__init__.py' not found (or not a regular file)
package init file 'yolox/layers/csrc/cocoeval/__init__.py' not found (or not a regular file)
package init file 'exps/example/__init__.py' not found (or not a regular file)
package init file 'exps/default/__init__.py' not found (or not a regular file)
package init file 'exps/example/mot/__init__.py' not found (or not a regular file)
package init file 'datasets/data_path/__init__.py' not found (or not a regular file)
package init file 'tutorials/trades/__init__.py' not found (or not a regular file)
package init file 'tutorials/ctracker/__init__.py' not found (or not a regular file)
package init file 'tutorials/transtrack/__init__.py' not found (or not a regular file)
package init file 'tutorials/cstrack/__init__.py' not found (or not a regular file)
package init file 'tutorials/centertrack/__init__.py' not found (or not a regular file)
package init file 'tutorials/jde/__init__.py' not found (or not a regular file)
package init file 'tutorials/qdtrack/__init__.py' not found (or not a regular file)
package init file 'tutorials/motr/__init__.py' not found (or not a regular file)
package init file 'tutorials/fairmot/__init__.py' not found (or not a regular file)
package init file 'tutorials/trades/mot_online/__init__.py' not found (or not a regular file)
package init file 'tutorials/ctracker/mot_online/__init__.py' not found (or not a regular file)
package init file 'tutorials/transtrack/mot_online/__init__.py' not found (or not a regular file)
package init file 'tutorials/centertrack/mot_online/__init__.py' not found (or not a regular file)
package init file 'tutorials/qdtrack/mot_online/__init__.py' not found (or not a regular file)
package init file 'tutorials/motr/mot_online/__init__.py' not found (or not a regular file)
reading manifest file 'yolox.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'yolox.egg-info/SOURCES.txt'
running build_ext
building 'yolox._C' extension
creating /home/mv/Documents/ByteTrack/build
[...]

Emitting ninja build file /home/mv/Documents/ByteTrack/build/temp.linux-aarch64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /home/mv/Documents/ByteTrack/build/temp.linux-aarch64-3.6/home/mv/Documents/ByteTrack/yolox/layers/csrc/cocoeval/cocoeval.o.d -pthread -B /home/mv/miniconda3/envs/VFZpy36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mv/Documents/ByteTrack/yolox/layers/csrc -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include/TH -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include/THC -I/home/mv/miniconda3/envs/VFZpy36/include/python3.6m -c -c /home/mv/Documents/ByteTrack/yolox/layers/csrc/cocoeval/cocoeval.cpp -o /home/mv/Documents/ByteTrack/build/temp.linux-aarch64-3.6/home/mv/Documents/ByteTrack/yolox/layers/csrc/cocoeval/cocoeval.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[2/2] c++ -MMD -MF /home/mv/Documents/ByteTrack/build/temp.linux-aarch64-3.6/home/mv/Documents/ByteTrack/yolox/layers/csrc/vision.o.d -pthread -B /home/mv/miniconda3/envs/VFZpy36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mv/Documents/ByteTrack/yolox/layers/csrc -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include/TH -I/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/include/THC -I/home/mv/miniconda3/envs/VFZpy36/include/python3.6m -c -c /home/mv/Documents/ByteTrack/yolox/layers/csrc/vision.cpp -o /home/mv/Documents/ByteTrack/build/temp.linux-aarch64-3.6/home/mv/Documents/ByteTrack/yolox/layers/csrc/vision.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating build/lib.linux-aarch64-3.6
creating build/lib.linux-aarch64-3.6/yolox
g++ -pthread -shared -B /home/mv/miniconda3/envs/VFZpy36/compiler_compat -L/home/mv/miniconda3/envs/VFZpy36/lib -Wl,-rpath=/home/mv/miniconda3/envs/VFZpy36/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/mv/Documents/ByteTrack/build/temp.linux-aarch64-3.6/home/mv/Documents/ByteTrack/yolox/layers/csrc/vision.o /home/mv/Documents/ByteTrack/build/temp.linux-aarch64-3.6/home/mv/Documents/ByteTrack/yolox/layers/csrc/cocoeval/cocoeval.o -L/home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-aarch64-3.6/yolox/_C.cpython-36m-aarch64-linux-gnu.so
copying build/lib.linux-aarch64-3.6/yolox/_C.cpython-36m-aarch64-linux-gnu.so -> yolox
Creating /home/mv/miniconda3/envs/VFZpy36/lib/python3.6/site-packages/yolox.egg-link (link to .)
yolox 0.1.0 is already the active version in easy-install.pth

Installed /home/mv/Documents/ByteTrack
Processing dependencies for yolox==0.1.0
Finished processing dependencies for yolox==0.1.0
```
