### ISSUE TITLE
Error when Training on Custom dataset

### ISSUE THREAD

**Issue by NaifahNurya** [ifzhang/ByteTrack#94]
Hi, 
Thanks for nice work,
I tried to use it in my dataset, and follow all instructions on how to train the model in a custom dataset.
How ever I got an error when training.

My dataset was in the same format as Cityperson dataset, 
mydatset
   |——————images
   |        └——————00001.jpg
   |        |—————— ...
   |        └——————0000N.jpg
   └——————labels_with_ids
            └——————00001.txt
            |—————— ...
            └——————0000N.txt

So I use "convert_cityperson_to_coco.py" to convert it to coco format., the process was succeful.

But when I train, I got  **KeyError: 'frame_id'**, details are shown below;

`
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\ByteTracker\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)

  File "C:\Users\admin\anaconda3\envs\ByteTracker\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
UnicodeEncodeError: 'cp949' codec can't encode character '\u2552' in position 87: illegal multibyte sequence
--- End of logging error ---
C:\Users\admin\anaconda3\envs\ByteTracker\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2021-11-28 12:29:52 | INFO     | yolox.core.trainer:130 - Model Summary: Params: 99.00M, Gflops: 791.73
2021-11-28 12:29:52 | INFO     | yolox.core.trainer:289 - loading checkpoint for fine tuning
2021-11-28 12:29:53 | WARNING  | yolox.utils.checkpoint:25 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 320, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([1, 320, 1, 1]).
2021-11-28 12:29:53 | WARNING  | yolox.utils.checkpoint:25 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([1]).
2021-11-28 12:29:53 | WARNING  | yolox.utils.checkpoint:25 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 320, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([1, 320, 1, 1]).
2021-11-28 12:29:53 | WARNING  | yolox.utils.checkpoint:25 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([1]).
2021-11-28 12:29:53 | WARNING  | yolox.utils.checkpoint:25 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 320, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([1, 320, 1, 1]).
2021-11-28 12:29:53 | WARNING  | yolox.utils.checkpoint:25 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([1]).
2021-11-28 12:29:55 | INFO     | yolox.data.datasets.mot:39 - loading annotations into memory...
2021-11-28 12:29:55 | INFO     | yolox.data.datasets.mot:39 - Done (t=0.00s)
2021-11-28 12:29:55--- Logging error in Loguru Handler #2 ---
 | Record was: {'elapsed': datetime.timedelta(seconds=5, microseconds=239804), 'exception': (type=<class 'KeyError'>, value=KeyError('frame_id'), traceback=<traceback object at 0x000001F84D881340>), 'extra': {}, 'file': (name='launch.py', path='c:\\users\\admin\\desktop\\kazi\\byte\\yolox\\core\\launch.py'), 'function': 'launch', 'level': (name='ERROR', no=40, icon='❌'), 'line': 90, 'message': "An error has been caught in function 'launch', process 'MainProcess' (6660), thread 'MainThread' (20320):", 'module': 'launch', 'name': 'yolox.core.launch', 'process': (id=6660, name='MainProcess'), 'thread': (id=20320, name='MainThread'), 'time': datetime(2021, 11, 28, 12, 29, 55, 256503, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400), 'India Time'))}
INFO     | pycocotools.coco:86 - creating index...
2021-11-28 12:29:55 | INFO     | pycocotools.coco:86 - Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\ByteTracker\lib\site-packages\loguru\_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
index created!  File "C:\Users\admin\Desktop\tracking\Byte\tools\train.py", line 101, in main
    trainer.train()
  File "c:\users\admin\desktop\tracking\byte\yolox\core\trainer.py", line 70, in train
    self.before_train()

  File "c:\users\admin\desktop\tracking\byte\yolox\core\trainer.py", line 143, in before_train
    self.train_loader = self.exp.get_data_loader(
  File "C:\Users\admin\Desktop\tracking\Byte\exps/example/mot\yolox_x_custom.py", line 43, in get_data_loader
    dataset = MOTDataset(
2021-11-28 12:29:55  File "c:\users\admin\desktop\tracking\byte\yolox\data\datasets\mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
  File "c:\users\admin\desktop\tracking\byte\yolox\data\datasets\mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
 |   File "c:\users\admin\desktop\tracking\byte\yolox\data\datasets\mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
  File "c:\users\admin\desktop\tracking\byte\yolox\data\datasets\mot.py", line 59, in load_anno_from_ids
    frame_id = im_ann["frame_id"]
KeyError: 'frame_id'

`

**The dataset I previously use it in FairMOT tracker and was successful trained.
Also, when I do demo using your pretrained model, the tracking video generated successful.**

My experiment carried out on window10

Kindly, any help to solve this problem.

**Comment by NaifahNurya** [comment]
More Details about Error and Dataset:

`
86
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 -   File "C:\Users\admin\anaconda3\envs\ByteTracker\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\admin\anaconda3\envs\ByteTracker\lib\site-packages\loguru\_file_sink.py", line 176, in write
    self._file.write(message)
index created!UnicodeEncodeError: 'cp949' codec can't encode character '\u2552' in position 476: illegal multibyte sequence
--- End of logging error ---

2021-11-29 09:02:20 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (10912), thread 'MainThread' (12644):
Traceback (most recent call last):

  File "C:\Users\admin\Desktop\Tracking\Byte\tools\train.py", line 115, in <module>
    launch(
    └ <function launch at 0x000001DB9E63F1F0>

> File "c:\users\admin\desktop\Tracking\byte\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001DBA020D280>

  File "C:\Users\admin\Desktop\Tracking\Byte\tools\train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001DBA01BD820>
    └ <yolox.core.trainer.Trainer object at 0x000001DBA0216490>

  File "c:\users\admin\desktop\Tracking\byte\yolox\core\trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000001DBA01DC9D0>
    └ <yolox.core.trainer.Trainer object at 0x000001DBA0216490>

  File "c:\users\admin\desktop\Tracking\byte\yolox\core\trainer.py", line 143, in before_train
    self.train_loader = self.exp.get_data_loader(
    │                   │    │   └ <function Exp.get_data_loader at 0x000001DBA021C040>
    │                   │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
    │                   └ <yolox.core.trainer.Trainer object at 0x000001DBA0216490>
    └ <yolox.core.trainer.Trainer object at 0x000001DBA0216490>

  File "C:\Users\admin\Desktop\Tracking\Byte\exps/example/mot\yolox_x_market.py", line 43, in get_data_loader
    dataset = MOTDataset(
              └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "c:\users\admin\desktop\Tracking\byte\yolox\data\datasets\mot.py", line 44, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function MOTDataset._load_coco_annotations at 0x000001DBA01DC550>
    │                  └ <yolox.data.datasets.mot.MOTDataset object at 0x000001DBCF705610>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x000001DBCF705610>

  File "c:\users\admin\desktop\Tracking\byte\yolox\data\datasets\mot.py", line 53, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
            │    │                                    └ <yolox.data.datasets.mot.MOTDataset object at 0x000001DBCF705610>
            │    └ <function MOTDataset.load_anno_from_ids at 0x000001DBA01DC5E0>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x000001DBCF705610>

  File "c:\users\admin\desktop\Tracking\byte\yolox\data\datasets\mot.py", line 53, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in self.ids]
            │    │                  │         │       │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
            │    │                  │         │       └ <yolox.data.datasets.mot.MOTDataset object at 0x000001DBCF705610>
            │    │                  │         └ 1
            │    │                  └ 1
            │    └ <function MOTDataset.load_anno_from_ids at 0x000001DBA01DC5E0>
            └ <yolox.data.datasets.mot.MOTDataset object at 0x000001DBCF705610>

  File "c:\users\admin\desktop\Tracking\byte\yolox\data\datasets\mot.py", line 59, in load_anno_from_ids
    frame_id = im_ann["frame_id"]
               └ {'file_name': 'market/data/images/set00/V000/set00_V000_00000.jpg', 'id': 1, 'height': 1080, 'width': 1920}

KeyError: 'frame_id'

`

But when I check in the `datasets\data_path`, we have the market.train, which gives the path for each iamges, and also in 
the `datasets\market\annotations`  we have train.json which was created after converting the data to coco format. Example f the details found in the train.son is as follows:

`
{"images": [{"file_name": "market/data/images/set00/V000/set00_V000_00000.jpg", "id": 1, "height": 1080, "width": 1920}, {"file_name": "market/data/images/set00/V000/set00_V000_00001.jpg", "id": 2, "height": 1080, "width": 1920},
.
.
.

"annotations": [{"id": 1, "category_id": 0, "image_id": 1, "track_id": -1, "bbox": [1736.199951171875, 690.1500244140625, 182.0800018310547, 274.3599853515625], "area": 49955.46663518064, "iscrowd": 0}, {"id": 2, "category_id": 0, "image_id": 1, "track_id": -1, "bbox": [1329.5999755859375, 712.6000366210938, 209.52000427246094, 361.6600036621094], "area": 75775.0055124634, "iscrowd": 0}, {"id": 3, "category_id": 0, "image_id": 1, "track_id": -1, "bbox": [823.3200073242188, 934.5899658203125, 516.2999877929688, 152.14999389648438], "area": 78555.03999145515, "iscrowd": 0},
.
.
.

`

**Comment by SachinGanesh** [comment]
Hi @NaifahNurya, were you able to solve this issue?

**Comment by NaifahNurya** [comment]
@SachinGanesh  Yes I solved it.

If your dataset is like mine with no ids, you can comment line number 59 and 60 of mot.py;

```
        #frame_id = im_ann["frame_id"]
        #video_id = im_ann["video_id"]
```
Then replace line number 84 (which is commented below), with the one in the next line (which not commented) below;

```
        #img_info = (height, width, frame_id, video_id, file_name)
        img_info = (height, width, file_name)
```
